export const CREATE_NEW_LEAD = "CREATE_NEW_LEAD";
export const TOGGLE_APPROVED = "TOGGLE_APPROVED";
export const CHANGE_FILTER_TYPE = "CHANGE_FILTER_TYPE";
export const CHANGE_LOADING_STATUS = "CHANGE_LOADING_STATUS";

export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
